Numpy pandas scikit-learn matplotlib 확인 : pip list

### 1. 넘파이
넘파이는 빠르고 효율적인 계산을 위해 만들어진 라이브러리이다.
고성능의 다차원 배열 객체를 계산할 효율적인 도구를 제공한다.

넘파이의 핵심은 ndarray객체이다. 동일한 자료형을 가지는 n차원의 배열을 기본으로 한다.

In [3]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim # axis(축)의 수 반환 # 2차원

2

In [5]:
a.shape # n*m

(2, 3)

In [6]:
a.size

6

In [7]:
a.dtype

dtype('int32')

In [9]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
b.ndim  # 3차원

3

In [11]:
b.shape  # (깊이, 행, 열)

(2, 2, 3)

In [12]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
# 넘파이 기본계산
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [15]:
a+b # 요소별 합

array([11, 22, 33])

In [16]:
np.add(a,b) # 요소별 합

array([11, 22, 33])

In [17]:
b-a # 요소별 차

array([ 9, 18, 27])

In [18]:
np.subtract(b,a) # 요소별 차

array([ 9, 18, 27])

In [19]:
a**2  # 제곱연산

array([1, 4, 9], dtype=int32)

In [20]:
a*b

array([10, 40, 90])

In [21]:
a/b

array([0.1, 0.1, 0.1])

In [22]:
b<15

array([ True, False, False])

### 축을 기준으로 한 연산

In [26]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# 행 방향
c.sum(axis=0)

array([5, 7, 9])

In [25]:
# 열 방향
c.sum(axis=1)

array([ 6, 15])

In [28]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [32]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
# 행방향
d.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [30]:
# 열방향
d.sum(axis=2)

array([[ 6, 15],
       [24, 33]])

In [31]:
# 깊이
d.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [33]:
# 1차원
e = np.array([1,2,3,4,5,6,7])

In [34]:
e[0]

1

In [35]:
e[-1]

7

In [36]:
e[:3] # 슬라이싱

array([1, 2, 3])

In [37]:
e[3:]

array([4, 5, 6, 7])

In [39]:
# 2차원
f = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [40]:
f[0,2]

3

In [41]:
f[1,0]

4

In [42]:
f[:,1]

array([2, 5, 8])

In [43]:
# 2차원 형태 그대로 추출
f[:, np.newaxis,1]

array([[2],
       [5],
       [8]])

In [45]:
f[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [46]:
f[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
# 배열 형태 변환

In [47]:
g = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

### ravel(), reshape(), T

In [49]:
# 1차원 쭉폄 -> np.ravel()
g.ravel() # 1차원 배열로

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
# n * m 변경
g.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
# 전치행렬
g.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### arange()

In [54]:
np.arange(32)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [55]:
h = np.arange(32).reshape((8, 4))

In [56]:
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
arr = np.zeros((8, 4))

### fancy indexindexing

##### 내가 원하는  것을   indexing하는 것

In [5]:
for i in range(8):
    arr[i] = i

In [6]:
arr[[4, 2, 6]] 

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.]])

In [7]:
arr[:, [1,3]]   # 1, 3번 열 뽑기 -

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])

### Series
#### - 1치원 배열과 같은 자료구조
#### -  numpy 어레이와 마찬가지로 인덱스 이용 가능하며, 인덱스를 지정할 수도 있다.

In [9]:
import pandas as pd
import numpy as np

In [10]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [11]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [12]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [13]:
obj2 = pd.Series([4, 7, -5, 3], index=['d','b','a','c'])
print(obj2)
obj2.index

d    4
b    7
a   -5
c    3
dtype: int64


Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [15]:
obj2[2]

-5

In [18]:
obj2['d'] = 6

In [19]:
obj2[['c', 'a', 'd']] # numpy fancy index와 유사

c    3
a   -5
d    6
dtype: int64

In [21]:
# boolean indexing
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [22]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [23]:
obj2 * 2
# list 와 차이는?

d    12
b    14
a   -10
c     6
dtype: int64

In [24]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [25]:
'b' in obj2

True

#### 즉, 여기까지 연습해보고 유추할 수 있는 것은 시리즈 객체 역시 리스트 객체와 마찬가지로 literable 하다는 것

In [26]:
[val for val in obj2]

[6, 7, -5, 3]

##### [연습1] obj2의 값에는 관심이 없고, 인덱스만 받아서 사용할 필요가 있을 때 인덱스 번호를 리스트로 저장해보세요

In [91]:
idx = [idx for idx,_ in enumerate(obj2)]

In [93]:
test = [[idx, value] for idx,value in enumerate(obj2)]

In [94]:
test[0]

[0, 6]

In [99]:
values = [i[1] for i in test]

In [100]:
values

[6, 7, -5, 3]

###### 시리즈 객체는 일차원의 구조이므로 딕셔너리 자료구조를 시리즈 객체로 변환하면 딕셔너리의 키는 행이름으로 사용된다.

In [101]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [102]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [114]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': [5000,6000]}

In [115]:
obj3 = pd.Series(sdata)
obj3

Ohio             35000
Texas            71000
Oregon           16000
Utah      [5000, 6000]
dtype: object

#### 그렇다면 위 obj3는 숫자 연산이 될까?

In [ ]:
# obj3 + 3

In [117]:
obj3[0] + 3

35003

In [119]:
#obj3[3] + 3

##### [연습2] obj2를 인덱스의 오름차순으로 정렬해보세요.

In [120]:
# 오름차순
obj2.sort_index()

a   -5
b    7
c    3
d    6
dtype: int64

In [121]:
obj2.sort_index(ascending=False)

d    6
c    3
b    7
a   -5
dtype: int64

### Data Frame 


In [ ]:
# Q1)  나이가 15세 초과인 데이터만 추출하고 싶다면( filtering or subsetting)

In [47]:
# Q2) 나이가 15세 초과 이거나 40세 미만인 데이터?

In [48]:
test = {'Name': ["John","Anna","Peter"],
       'Location':["New Yotk","Paris","Berlin"],
       'Age':[24,13,45]}

In [49]:
type(test)

dict

In [50]:
test_pd = pd.DataFrame(test)

In [51]:
test_pd

Name  Location  Age
0   John  New Yotk   24
1   Anna     Paris   13
2  Peter    Berlin   45

In [53]:
# 1)
test_pd[test_pd.Age > 15]

Name  Location  Age
0   John  New Yotk   24
2  Peter    Berlin   45

In [52]:
# 2) 
test_pd[(test_pd.Age > 15)&(test_pd.Age < 40)]

# precedence and Associativity of Operators
# 우선 순위 참고 자료 : https://www.programiz.com/python-programming/precedence-associativity

Name  Location  Age
0  John  New Yotk   24

In [54]:
#  operator procedure

2+-1

1

In [55]:
5--2

7

In [79]:
### 자료의 행수가 맞지 않을 때 데이터프레임화??

test1 = {'Name': ["John", "Anna", "Peter", "Adam"],
        'Location':["New York", "Paris", "Berlin"],
        'Age':[24, 13, 45]}

In [80]:
# error=?

#pd.DataFrame(test1)

In [81]:
test_df1 = \
pd.DataFrame.from_dict(test1, orient='index')

In [82]:
test_df1

0      1       2     3
Name          John   Anna   Peter  Adam
Location  New York  Paris  Berlin  None
Age             24     13      45  None

In [83]:
test_df1.T

Name  Location   Age
0   John  New York    24
1   Anna     Paris    13
2  Peter    Berlin    45
3   Adam      None  None

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html

In [86]:
test_pd = pd.DataFrame(test)

In [87]:
test_pd

Name  Location  Age
0   John  New Yotk   24
1   Anna     Paris   13
2  Peter    Berlin   45

### pandas 기본 인덱싱

### 컬럼 추출
#### - 기본형 : 컬럼은 이름으로/행은 인덱스 번호로
#### - 그러나 행 추출의 경우 슬라이싱만 가능함

In [88]:
# 1개 컬럼
test_pd['Name']

0     John
1     Anna
2    Peter
Name: Name, dtype: object

In [89]:
test_pd['Name'][0]+'1'

'John1'

In [90]:
# 1개 컬럼
test_pd[['Name']]

# 추추할 때 데이터프레임 형태로 줌

Name
0   John
1   Anna
2  Peter

In [98]:
for i in test_pd[['Name']]:
    print(i)

# 여기에서 보시다 시피 컬럼명 : 'Name'에 접근했음을 알 수 있음.

Name


In [97]:
for i in test_pd[['Name']]['Name']:
    print(i)

John
Anna
Peter


In [106]:
test_pd['Name'][[0,2]]  # Series는 이렇게 추출 가능.

0     John
2    Peter
Name: Name, dtype: object

In [107]:
# 하지만 데이터 프레임 형태로 추출시 슬라이싱만 가능.

test_pd[['Name']][:2]

Name
0  John
1  Anna

In [108]:
# 2개 컬럼 -> 리스트로 전달
test_pd[['Name', 'Location']]

Name  Location
0   John  New Yotk
1   Anna     Paris
2  Peter    Berlin

In [109]:
test_pd[:2]

Name  Location  Age
0  John  New Yotk   24
1  Anna     Paris   13

In [110]:
test_pd[:1]

Name  Location  Age
0  John  New Yotk   24

##### 더 연습해보기

In [112]:
data = {'state': ['Ohio']*3+['Nevada']*3,
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [113]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [122]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [123]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [124]:
frame.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [125]:
# 데이터프레임의 기본정보 보기
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   6 non-null      object 
 1   year    6 non-null      int64  
 2   pop     6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 272.0+ bytes


In [127]:
# 데이터프레임의 기본통계량 보기
frame.describe()

year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [128]:
# 컬럼 순서 변경
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [129]:
frame_test = frame[['year', 'state', 'pop']]
frame_test

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [131]:
# 없는 컬럼 추가

frame2 = \  # 줄바꿈
pd.DataFrame(data,
            columns=['year', 'state', 'pop', 'debt'],
            index=['one','two','three','four','five','six'])

In [133]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [134]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

#### 특정 컬럼에 값 넣기

In [136]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

#### 특정 컬럼 추가

In [138]:
frame2['debt/pop'] = frame2['debt']/frame2['pop']

In [139]:
frame2

year   state  pop  debt   debt/pop
one    2000    Ohio  1.5  16.5  11.000000
two    2001    Ohio  1.7  16.5   9.705882
three  2002    Ohio  3.6  16.5   4.583333
four   2001  Nevada  2.4  16.5   6.875000
five   2002  Nevada  2.9  16.5   5.689655
six    2003  Nevada  3.2  16.5   5.156250

In [140]:
frame2['debt/pop*100'] = frame2['debt/pop'] * 100

In [141]:
frame2

year   state  pop  debt   debt/pop  debt/pop*100
one    2000    Ohio  1.5  16.5  11.000000   1100.000000
two    2001    Ohio  1.7  16.5   9.705882    970.588235
three  2002    Ohio  3.6  16.5   4.583333    458.333333
four   2001  Nevada  2.4  16.5   6.875000    687.500000
five   2002  Nevada  2.9  16.5   5.689655    568.965517
six    2003  Nevada  3.2  16.5   5.156250    515.625000

In [142]:
# null값으로 컬럼 추가
frame2['etc'] = np.NaN

In [143]:
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc
one    2000    Ohio  1.5  16.5  11.000000   1100.000000  NaN
two    2001    Ohio  1.7  16.5   9.705882    970.588235  NaN
three  2002    Ohio  3.6  16.5   4.583333    458.333333  NaN
four   2001  Nevada  2.4  16.5   6.875000    687.500000  NaN
five   2002  Nevada  2.9  16.5   5.689655    568.965517  NaN
six    2003  Nevada  3.2  16.5   5.156250    515.625000  NaN

In [144]:
# null 확인
pd.isnull(frame2['etc'])

one      True
two      True
three    True
four     True
five     True
six      True
Name: etc, dtype: bool

In [145]:
pd.isna(frame2['etc'])

one      True
two      True
three    True
four     True
five     True
six      True
Name: etc, dtype: bool

In [146]:
# 1개의 값으로 채워넣기
frame2['etc'] = 50

In [147]:
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc
one    2000    Ohio  1.5  16.5  11.000000   1100.000000   50
two    2001    Ohio  1.7  16.5   9.705882    970.588235   50
three  2002    Ohio  3.6  16.5   4.583333    458.333333   50
four   2001  Nevada  2.4  16.5   6.875000    687.500000   50
five   2002  Nevada  2.9  16.5   5.689655    568.965517   50
six    2003  Nevada  3.2  16.5   5.156250    515.625000   50

In [ ]:
# 결측치 찾고 확인 => 보간법 

#https://teddylee777.github.io/pandas/pandas-interpolation

In [148]:
# 서로 다른 값으로 채워 넣기 --> 행수에 맞는 리스트로 추가
frame2['etc2'] = [i for i in range(12) if i%2 == 0]

In [149]:
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc  etc2
one    2000    Ohio  1.5  16.5  11.000000   1100.000000   50     0
two    2001    Ohio  1.7  16.5   9.705882    970.588235   50     2
three  2002    Ohio  3.6  16.5   4.583333    458.333333   50     4
four   2001  Nevada  2.4  16.5   6.875000    687.500000   50     6
five   2002  Nevada  2.9  16.5   5.689655    568.965517   50     8
six    2003  Nevada  3.2  16.5   5.156250    515.625000   50    10

In [150]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc  etc2
one    2000    Ohio  1.5   0.0  11.000000   1100.000000   50     0
two    2001    Ohio  1.7   1.0   9.705882    970.588235   50     2
three  2002    Ohio  3.6   2.0   4.583333    458.333333   50     4
four   2001  Nevada  2.4   3.0   6.875000    687.500000   50     6
five   2002  Nevada  2.9   4.0   5.689655    568.965517   50     8
six    2003  Nevada  3.2   5.0   5.156250    515.625000   50    10

In [152]:
val = pd.Series([-1.2, -1.5, -1.7],
               index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [153]:
frame2['debt'] = val
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc  etc2
one    2000    Ohio  1.5   NaN  11.000000   1100.000000   50     0
two    2001    Ohio  1.7  -1.2   9.705882    970.588235   50     2
three  2002    Ohio  3.6   NaN   4.583333    458.333333   50     4
four   2001  Nevada  2.4  -1.5   6.875000    687.500000   50     6
five   2002  Nevada  2.9  -1.7   5.689655    568.965517   50     8
six    2003  Nevada  3.2   NaN   5.156250    515.625000   50    10

In [154]:
# 논리값 채워넣기
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt   debt/pop  debt/pop*100  etc  etc2  eastern
one    2000    Ohio  1.5   NaN  11.000000   1100.000000   50     0     True
two    2001    Ohio  1.7  -1.2   9.705882    970.588235   50     2     True
three  2002    Ohio  3.6   NaN   4.583333    458.333333   50     4     True
four   2001  Nevada  2.4  -1.5   6.875000    687.500000   50     6    False
five   2002  Nevada  2.9  -1.7   5.689655    568.965517   50     8    False
six    2003  Nevada  3.2   NaN   5.156250    515.625000   50    10    False

In [155]:
# 컬럼 삭제

del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'debt/pop', 'debt/pop*100', 'etc',
       'etc2'],
      dtype='object')

In [156]:
# 컬럼 삭제
frame2 = frame2[['year', 'state', 'pop', 'debt']]
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

### 특정 인덱스 버리기

In [158]:
obj = pd.Series(np.arange(5.),
               index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [160]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [161]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [162]:
# frame2 적용해보기
frame3 = frame2.drop(['two','four'])

In [163]:
frame3

year   state  pop  debt
one    2000    Ohio  1.5   NaN
three  2002    Ohio  3.6   NaN
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [164]:
# 숫자 인덱스로 재정리
frame3.reset_index(drop=True)

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2002    Ohio  3.6   NaN
2  2002  Nevada  2.9  -1.7
3  2003  Nevada  3.2   NaN

In [165]:
# 기존 행이름(인덱스 어트리뷰트)을 컬럼으로 사용하려면
frame3.reset_index()

index  year   state  pop  debt
0    one  2000    Ohio  1.5   NaN
1  three  2002    Ohio  3.6   NaN
2   five  2002  Nevada  2.9  -1.7
3    six  2003  Nevada  3.2   NaN

### 데이터프레임 인덱스 생성

In [166]:
test_df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                      columns=['one','two','three','four'])

In [167]:
test_df

one  two  three  four
0    0    1      2     3
1    4    5      6     7
2    8    9     10    11
3   12   13     14    15

In [168]:
# 하나의 컬럼 추출 :  Series 객체

test_df['one']

0     0
1     4
2     8
3    12
Name: one, dtype: int32

In [169]:
test_df['one'][1]

4

In [170]:
test_df[['four', 'two']][:2]

four  two
0     3    1
1     7    5

In [179]:
#### QUIZ) 위의 0,2 행만 추출하고 싶다면 어떻게 해야할까?
test_df.reindex([0,2])

one  two  three  four
0    0    1      2     3
2    8    9     10    11

In [180]:
test_df[['four','two']][test_df.index%2==0]

four  two
0     3    1
2    11    9

In [181]:
test_df.drop(['two','four'],axis=1)

one  three
0    0      2
1    4      6
2    8     10
3   12     14

### 인덱싱 이름 

In [182]:
import pandas as pd
import numpy as np

In [183]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [184]:
# quiz)
data

#1) three 컬럼 값이 5보다 큰 모든 행 추출
#2) 위 데이터프레임에서 5보다 작은 값은 0으로 대체

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [196]:
data[data['three'] > 5]
    

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [195]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [194]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc
#### - loc : 행이름을 활용한 인덱싱 - 인덱스 기준
#### - iloc : 정수 색인 방식 -- 데이터 순서 기준

### 1.loc

In [197]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [198]:
data1 = data.reset_index()

In [199]:
data1

index  one  two  three  four
0      Ohio    0    0      0     0
1  Colorado    0    5      6     7
2      Utah    8    9     10    11
3  New York   12   13     14    15

### 콜로라도와 뉴욕 추출

In [200]:
data1

index  one  two  three  four
0      Ohio    0    0      0     0
1  Colorado    0    5      6     7
2      Utah    8    9     10    11
3  New York   12   13     14    15

In [205]:
data1.loc[[1,3]][['one','three']]

one  three
1    0      6
3   12     14

In [206]:
data1.loc[[1,3]][['one','three']].loc[3]

one      12
three    14
Name: 3, dtype: int32

In [208]:
# error
#data.loc[[1, 3]]

In [210]:
data.loc['Colorado', ['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [212]:
data.loc[['Colorado', 'Ohio'],['two','three']]

two  three
Colorado    5      6
Ohio        0      0

In [213]:
test_df.loc[:2, ['two', 'three']]

two  three
0    1      2
1    5      6
2    9     10

## 연습문제

In [225]:
gdp = pd.read_csv("gdp2018.csv")

In [226]:
gdp

Code              Nation       GDP
0   GBR      United Kingdom   3074432
1   JPN               Japan   5484951
2   IND               India  10498468
3   USA       United States  20494100
4   RUS  Russian Federation   3986064
5   KOR          Korea Rep.   2090161
6   FRA              France   3073179
7   ITA               Italy   2542974
8   AUS           Australia   1288228
9   TUR              Turkey   2372087
10  DEU             Germany   4505236
11  MEX              Mexico   2519962
12  THA            Thailand   1320373
13  SAU        Saudi Arabia   1857538
14  IRN   Iran Islamic Rep.   1695064
15  CHN               China  25361744
16  IDN           Indonesia   3494762
17  ESP               Spain   1908879
18  BRA              Brazil   3365757
19  CAN              Canada   1774034


1. GDP 데이터를 이용해 아래 문제에 해당하는 데이터만 추출해보세요 

*(결과만 데이터프레임 형태로 확인할 수 있으면 됩니다)*

0) Ranking 컬럼 추가

1) 상위 5개국의 국가 코드명과 랭킹 컬럼

2) 중국, 일본, 한국의 랭킹과 GDP 컬럼

3) 랭킹이 홀수인 국가들의 코드, 랭킹, GDP 컬럼

4) 랭킹이 짝수이면서 10위 이하 국가들의 코드, 랭킹, GDP 컬럼


In [230]:
#0 Ranking 컬럼 추가

gdp['Ranking'] = gdp['GDP'].rank(method='min', ascending=False)

In [231]:
gdp

Code              Nation       GDP  Ranking
0   GBR      United Kingdom   3074432      9.0
1   JPN               Japan   5484951      4.0
2   IND               India  10498468      3.0
3   USA       United States  20494100      2.0
4   RUS  Russian Federation   3986064      6.0
5   KOR          Korea Rep.   2090161     14.0
6   FRA              France   3073179     10.0
7   ITA               Italy   2542974     11.0
8   AUS           Australia   1288228     20.0
9   TUR              Turkey   2372087     13.0
10  DEU             Germany   4505236      5.0
11  MEX              Mexico   2519962     12.0
12  THA            Thailand   1320373     19.0
13  SAU        Saudi Arabia   1857538     16.0
14  IRN   Iran Islamic Rep.   1695064     18.0
15  CHN               China  25361744      1.0
16  IDN           Indonesia   3494762      7.0
17  ESP               Spain   1908879     15.0
18  BRA              Brazil   3365757      8.0
19  CAN              Canada   1774034     17.0

In [260]:
#1 상위 5개국의 국가 코드명과 랭킹 컬럼

gdp2[gdp['Ranking'] <= 5][['Code', 'Ranking']]

<ipython-input-260-96c1570c1fa2>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  gdp2[gdp['Ranking'] <= 5][['Code', 'Ranking']]


Code  Ranking
1   JPN      4.0
2   IND      3.0
3   USA      2.0
10  DEU      5.0
15  CHN      1.0

In [270]:
#2 중국, 일본, 한국의 랭킹과 GDP 컬럼

gdp.reindex([1, 5, 15])

Code      Nation       GDP  Ranking
1   JPN       Japan   5484951      4.0
5   KOR  Korea Rep.   2090161     14.0
15  CHN       China  25361744      1.0

In [ ]:
# 3) 랭킹이 홀수인 국가들의 코드, 랭킹, GDP 컬럼

In [272]:
gdp[gdp['Ranking'] % 2 != 0][['Code', 'Ranking', 'GDP']]

Code  Ranking       GDP
0   GBR      9.0   3074432
2   IND      3.0  10498468
7   ITA     11.0   2542974
9   TUR     13.0   2372087
10  DEU      5.0   4505236
12  THA     19.0   1320373
15  CHN      1.0  25361744
16  IDN      7.0   3494762
17  ESP     15.0   1908879
19  CAN     17.0   1774034

In [ ]:
# 4) 랭킹이 짝수이면서 10위 이하 국가들의 코드, 랭킹, GDP 컬럼

In [273]:
gdp[(gdp['Ranking'] % 2 == 0) & (gdp['Ranking'] <= 10)][['Code', 'Ranking', 'GDP']]

Code  Ranking       GDP
1   JPN      4.0   5484951
3   USA      2.0  20494100
4   RUS      6.0   3986064
6   FRA     10.0   3073179
18  BRA      8.0   3365757

2. “성별;직업;나이;이름”의 데이터를 [“이름”,“나이”,“직업”]으로 변경하는 코드를 작성해보세요(optional)

In [5]:
data = "성별;직업;나이;이름"

In [9]:
data = data.split(";")

In [10]:
data

['성별', '직업', '나이', '이름']

In [12]:
data[0] = data[3]

In [13]:
data

['이름', '직업', '나이', '이름']

In [15]:
data[3] = data[1]

In [16]:
data

['이름', '직업', '나이', '직업']

In [17]:
data[1] = data[2]

In [18]:
data

['이름', '나이', '나이', '직업']

In [19]:
data[2] = data[3]

In [25]:
data.pop(3)

In [23]:
data

['이름', '나이', '직업']

In [13]:
# 다른 방법
import numpy as np
data = "성별;직업;나이;이름"

In [14]:
data = data.split(";")

In [15]:
a = np.array(data)

In [16]:
b = list(a[1:4])

In [18]:
b.reverse()